name:                han2zen
version:             0.1.0.0
github:              "wataru86/han2zen"
license:             BSD3
author:              "wataru"
maintainer:          "is151086@cis.aichi-pu.ac.jp"
copyright:           "Copyright (c) 2018 Wataru Yamada"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src

tests:
  han2zen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - han2zen
